bzl/xfail: Improve error messages

diff --git a/bzl/run_xfail_test b/bzl/run_xfail_test
--- a/bzl/run_xfail_test
+++ b/bzl/run_xfail_test
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 #
-# SPDX-FileCopyrightText: 2022-2025 Robin Lindén <dev@robinlinden.eu>
+# SPDX-FileCopyrightText: 2022-2026 Robin Lindén <dev@robinlinden.eu>
 #
 # SPDX-License-Identifier: BSD-2-Clause
 
@@ -16,7 +16,12 @@ echo "Running test ${TEST_BINARY}" "$@" >&2
 RESULT="$?"
 set -e
 
-if [ "${RESULT}" -ne 1 ]; then
+if [ "${RESULT}" -eq 0 ]; then
   echo "Test succeeded when it should have exploded" >&2
+  exit 1
+elif [ "${RESULT}" -eq 1 ]; then
+  echo "Test failed as expected" >&2
+else
+  echo "Test failed with unexpected exit code ${RESULT}" >&2
   exit 1
 fi
